FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
COPY mvnw .
COPY .mvn ./.mvn
RUN chmod +x mvnw && ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Importar certificados FNMT (CA que firma el certificado del INE)
COPY src/main/resources/certs/fnmt_raiz.cer /tmp/fnmt_raiz.cer
COPY src/main/resources/certs/fnmt_componentes.cer /tmp/fnmt_componentes.cer
RUN keytool -import -alias fnmt-raiz \
    -keystore $JAVA_HOME/lib/security/cacerts \
    -file /tmp/fnmt_raiz.cer \
    -storepass changeit -noprompt && \
    keytool -import -alias fnmt-componentes \
    -keystore $JAVA_HOME/lib/security/cacerts \
    -file /tmp/fnmt_componentes.cer \
    -storepass changeit -noprompt && \
    rm /tmp/fnmt_raiz.cer /tmp/fnmt_componentes.cer

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]